### ISSUE TITLE
Dont word in TLD v2.31

### ISSUE THREAD

**Issue by CoffeeSwt** [B1gF1s4/TLD-RecordingUtils#1]
How to toggle freebird cam on/off? I didn't find the key in the settings. I use the command by press F1 and input `fly`, but the speed of the cam what i'v changed didn't work. 
Also I got some errors in MelonLoader Console. 
![image](https://github.com/B1gF1s4/TLD-RecordingUtils/assets/83854560/b5712b66-e98f-49c2-82bd-c3ed0668e10a)
![image](https://github.com/B1gF1s4/TLD-RecordingUtils/assets/83854560/c8508362-5102-4fc3-bfdf-0b43d551ed94)

**Comment by B1gF1s4** [comment]
dev console command cam_freebird toggles the freebird cam which has its own speed settings. flymode speed only affect regular fly mode.
errors in logs were fixed by updating dependencies.
